name: Deploy Node Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t sreeharirs/rentalmall .
      
      - name: Publish image to Docker Hub
        run: docker push sreeharirs/rentalmall:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull sreeharirs/rentalmall:latest
      
      - name: Run Docker container
        run: |
          docker stop rentalmall-container || true
          docker rm rentalmall-container || true
          docker run -d -p 5000:5000 --name rentalmall-container \
            -e PRISMA_PASSWORD='${{ secrets.PRISMA_PASSWORD }}' \
            -e PUSHER_APP_ID='${{ secrets.PUSHER_APP_ID }}' \
            -e NEXT_PUBLIC_PUSHER_APP_KEY='${{ secrets.NEXT_PUBLIC_PUSHER_APP_KEY }}' \
            -e PUSHER_SECRET='${{ secrets.PUSHER_SECRET }}' \
            -e PUSHER_CLUSTER='${{ secrets.PUSHER_CLUSTER }}' \
            -e RAZORPAY_KEY_ID='${{ secrets.RAZORPAY_KEY_ID }}' \
            -e RAZORPAY_KEY_SECRET='${{ secrets.RAZORPAY_KEY_SECRET }}' \
            -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            sreeharirs/rentalmall